name: Dependency Review
on: pull_request
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/dependency-review-action@65e9ec79cca0cf5f6b74269aa48c9a1a836d1c35 # v4
